return {
  "neovim/nvim-lspconfig",
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  "ray-x/lsp_signature.nvim",
  "j-hui/fidget.nvim",
  "mrshmllow/document-color.nvim",
  "jose-elias-alvarez/null-ls.nvim",
  "mfussenegger/nvim-jdtls",
  "simrat39/rust-tools.nvim",
  "jose-elias-alvarez/typescript.nvim",
  "b0o/schemastore.nvim",
  "folke/neodev.nvim",
}
